export const GAMES = [
  {
    id: 'tower-defense',
    title: 'Защита от зомби',
    description: 'Tower defense в стиле Plants vs Zombies. Сажайте растения и отбивайте волны зомби.',
    icon: '🌻',
    url: 'games/tower-defense/',
    available: true,
    tags: ['стратегия', 'tower defense'],
  },
  {
    id: 'math-columns',
    title: 'Столбик',
    description: 'Сложение и вычитание столбиком',
    icon: '📐',
    url: 'games/math-columns/',
    available: true,
    tags: ['математика', 'обучение'],
  },
  {
    id: 'snake',
    title: 'Змейка',
    description: 'Классическая аркада — собирайте яблоки и не врезайтесь в стены.',
    icon: '🐍',
    url: 'games/snake/',
    available: false,
    tags: ['аркада', 'классика'],
  },
  {
    id: 'breakout',
    title: 'Арканоид',
    description: 'Разбивайте блоки мячом и не дайте ему упасть.',
    icon: '🧱',
    url: 'games/breakout/',
    available: false,
    tags: ['аркада'],
  },
  {
    id: 'memory',
    title: 'Найди пару',
    description: 'Запоминайте карточки и находите одинаковые пары.',
    icon: '🃏',
    url: 'games/memory/',
    available: false,
    tags: ['головоломка'],
  },
];
